apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: NodePort
  selector:
    app: deployment1
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005

---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: NodePort
  selector:
    app: deployment2
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005