apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-prod
spec:
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: '<YOUR Manifest Repo>'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.production.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true